---
#
# Ansible managed
#
repository:
  description: Deploys and configure Elastic beats
  homepage: https://buluma.github.io/
  topics: monitoring, logging, security, metrics, topbeat, filebeat, elk, ansible, molecule, tox, playbook
