---
- name: topbeat | Copy Topbeat config file.
  become: true
  ansible.builtin.template:
    src: topbeat.yml.j2
    dest: /etc/topbeat/topbeat.yml
    mode: "0644"
    owner: root
    group: root
    validate: "/usr/bin/topbeat -configtest -c %s"
  notify: Restart topbeat

- name: topbeat | Start Topbeat service.
  become: true
  ansible.builtin.service:
    name: topbeat
    state: started
    enabled: true
