---
- name: Restart filebeat
  become: yes
  service:
    name: filebeat
    state: restarted

- name: restart packetbeat
  become: yes
  service:
    name: topbeat
    state: restarted

- name: restart heartbeat
  become: yes
  service:
    name: heartbeat
    state: restarted

- name: restart metricbeat
  become: yes
  service:
    name: metricbeat
    state: restarted
